### API Informations
GET http://localhost:3000/api

### API 404
GET http://localhost:3000/api/randomthings

### Récupération de toutes les catégories
GET http://localhost:3000/api/categories

### Récupération de tous les articles
GET http://localhost:3000/api/posts

### Récupération d'un article par son ID
GET http://localhost:3000/api/posts/2

### Récupération des articles d'une catégorie
GET http://localhost:3000/api/posts/category/3