### API 404
GET http://localhost:3000/api/randomthings

### Récupération de toutes les catégories
GET http://localhost:3000/api/categories

### Récupération de tous les articles
GET http://localhost:3000/api/posts